### ISSUE TITLE
How does it work with headers and API keys?

### ISSUE THREAD

**Issue by ericxin1982** [markmead/alpinejs-axios#2]
Hi @markmead 

I saw your example, looked tidy, and how about request header info, like api key or jwt key, how to bind together?

Thanks
Eric Xin

**Comment by markmead** [comment]
Have you tried just passing them in the options? 

```js
await $get('https://dummyjson.com/products/1', {
  headers: {},
  apiKey: ''
})
```

**Comment by ericxin1982** [comment]
Oh, I saw it. Thanks for your help.

**Comment by c-nv-s** [comment]
came looking for an example with headers and body payload so might be useful to put that in the readme as well
